"""index runs.user_id for the active + recently-finished poll

Hand-written (not autogenerated — the shared dev DB carries orphan tables that
autogenerate would try to drop). `GET /runs/active?recent_seconds=…` now reads
terminal rows by user, which the partial `ix_runs_active` index can't serve.

Revision ID: a1f4c7d2e9b3
Revises: d4e8f1a6c9b2
Create Date: 2026-07-07 00:00:00.000000

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a1f4c7d2e9b3"
down_revision: str | Sequence[str] | None = "d4e8f1a6c9b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_index("ix_runs_user_id", "runs", ["user_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_runs_user_id", table_name="runs")
