"""add runs table + threads.last_run_status

Hand-written (not autogenerated — the shared dev DB carries orphan tables that
autogenerate would try to drop). Moves run records from Redis to Postgres; the
event log / cancel / liveness stay in Redis. No data migration: the old Redis
records were 1h-TTL ephemeral and simply expire.

Revision ID: d4e8f1a6c9b2
Revises: b6d1c8e4f2a7
Create Date: 2026-07-07 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d4e8f1a6c9b2"
down_revision: str | Sequence[str] | None = "b6d1c8e4f2a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "multitask_strategy", sa.String(), nullable=False, server_default="reject"
        ),
        sa.Column("input", postgresql.JSONB(), nullable=True),
        sa.Column("command", postgresql.JSONB(), nullable=True),
        sa.Column("trigger", sa.String(), nullable=True),
        sa.Column("config_overrides", postgresql.JSONB(), nullable=True),
        sa.Column("output_schema", postgresql.JSONB(), nullable=True),
        sa.Column("delivery", postgresql.JSONB(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Run history per thread, newest first.
    op.create_index(
        "ix_runs_thread_id_created_at",
        "runs",
        ["thread_id", "created_at"],
        unique=False,
    )
    # The per-thread mutex: at most one running run per thread, enforced by the
    # database instead of a Redis SET NX + TTL heartbeat.
    op.create_index(
        "uq_runs_one_running_per_thread",
        "runs",
        ["thread_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    # The hot set: dispatcher claim (pending) + active-runs poll + reaper
    # worklist. Partial, so it only ever holds in-flight runs.
    op.create_index(
        "ix_runs_active",
        "runs",
        ["status", "user_id"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )

    # Outcome of a thread's most recent run, stamped transactionally with the
    # run's terminal update. NULL = no finished run recorded (no backfill).
    op.add_column("threads", sa.Column("last_run_status", sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("threads", "last_run_status")

    op.drop_index("ix_runs_active", table_name="runs")
    op.drop_index("uq_runs_one_running_per_thread", table_name="runs")
    op.drop_index("ix_runs_thread_id_created_at", table_name="runs")
    op.drop_table("runs")
