"""create_official_mcp_servers_and_add_description

Revision ID: ee903a5e6aa0
Revises: 09bb4fe47733
Create Date: 2025-12-18 15:12:53.326581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ee903a5e6aa0'
down_revision: Union[str, Sequence[str], None] = '09bb4fe47733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create official_mcp_servers table with same structure as mcp_servers
    op.create_table('official_mcp_servers',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_type', postgresql.ENUM('none', 'api_key', 'oauth2', name='mcp_auth_type', create_type=False), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # Add description column to mcp_servers table
    op.add_column('mcp_servers', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove description column from mcp_servers table
    op.drop_column('mcp_servers', 'description')

    # Drop official_mcp_servers table
    op.drop_table('official_mcp_servers')
    # ### end Alembic commands ###
